package com.cyong.model;

import java.util.Date;

public class BlogTagRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_tag_relation.btrelation_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Long btrelationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_tag_relation.btrelation_blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Long btrelationBlogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_tag_relation.btrelation_tag_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer btrelationTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_tag_relation.btrelation_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date btrelationCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog_tag_relation.btrelation_id
     *
     * @return the value of tb_blog_tag_relation.btrelation_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Long getBtrelationId() {
        return btrelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog_tag_relation.btrelation_id
     *
     * @param btrelationId the value for tb_blog_tag_relation.btrelation_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBtrelationId(Long btrelationId) {
        this.btrelationId = btrelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog_tag_relation.btrelation_blog_id
     *
     * @return the value of tb_blog_tag_relation.btrelation_blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Long getBtrelationBlogId() {
        return btrelationBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog_tag_relation.btrelation_blog_id
     *
     * @param btrelationBlogId the value for tb_blog_tag_relation.btrelation_blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBtrelationBlogId(Long btrelationBlogId) {
        this.btrelationBlogId = btrelationBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog_tag_relation.btrelation_tag_id
     *
     * @return the value of tb_blog_tag_relation.btrelation_tag_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getBtrelationTagId() {
        return btrelationTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog_tag_relation.btrelation_tag_id
     *
     * @param btrelationTagId the value for tb_blog_tag_relation.btrelation_tag_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBtrelationTagId(Integer btrelationTagId) {
        this.btrelationTagId = btrelationTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog_tag_relation.btrelation_create_time
     *
     * @return the value of tb_blog_tag_relation.btrelation_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getBtrelationCreateTime() {
        return btrelationCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog_tag_relation.btrelation_create_time
     *
     * @param btrelationCreateTime the value for tb_blog_tag_relation.btrelation_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBtrelationCreateTime(Date btrelationCreateTime) {
        this.btrelationCreateTime = btrelationCreateTime;
    }
}