package com.cyong.model;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Long blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_title
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_sub_url
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String blogSubUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_cover_image
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String blogCoverImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_category_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer blogCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_tags
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String blogTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_status
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Byte blogStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_views
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Long blogViews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_likes
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Long blogLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_enable_comment
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Byte blogEnableComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_is_deleted
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Byte blogIsDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date blogCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date blogUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog.blog_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_id
     *
     * @return the value of tb_blog.blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_id
     *
     * @param blogId the value for tb_blog.blog_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_title
     *
     * @return the value of tb_blog.blog_title
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_title
     *
     * @param blogTitle the value for tb_blog.blog_title
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_sub_url
     *
     * @return the value of tb_blog.blog_sub_url
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getBlogSubUrl() {
        return blogSubUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_sub_url
     *
     * @param blogSubUrl the value for tb_blog.blog_sub_url
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogSubUrl(String blogSubUrl) {
        this.blogSubUrl = blogSubUrl == null ? null : blogSubUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_cover_image
     *
     * @return the value of tb_blog.blog_cover_image
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getBlogCoverImage() {
        return blogCoverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_cover_image
     *
     * @param blogCoverImage the value for tb_blog.blog_cover_image
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogCoverImage(String blogCoverImage) {
        this.blogCoverImage = blogCoverImage == null ? null : blogCoverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_category_id
     *
     * @return the value of tb_blog.blog_category_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getBlogCategoryId() {
        return blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_category_id
     *
     * @param blogCategoryId the value for tb_blog.blog_category_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogCategoryId(Integer blogCategoryId) {
        this.blogCategoryId = blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_tags
     *
     * @return the value of tb_blog.blog_tags
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getBlogTags() {
        return blogTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_tags
     *
     * @param blogTags the value for tb_blog.blog_tags
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogTags(String blogTags) {
        this.blogTags = blogTags == null ? null : blogTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_status
     *
     * @return the value of tb_blog.blog_status
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Byte getBlogStatus() {
        return blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_status
     *
     * @param blogStatus the value for tb_blog.blog_status
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogStatus(Byte blogStatus) {
        this.blogStatus = blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_views
     *
     * @return the value of tb_blog.blog_views
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Long getBlogViews() {
        return blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_views
     *
     * @param blogViews the value for tb_blog.blog_views
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogViews(Long blogViews) {
        this.blogViews = blogViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_likes
     *
     * @return the value of tb_blog.blog_likes
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Long getBlogLikes() {
        return blogLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_likes
     *
     * @param blogLikes the value for tb_blog.blog_likes
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogLikes(Long blogLikes) {
        this.blogLikes = blogLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_enable_comment
     *
     * @return the value of tb_blog.blog_enable_comment
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Byte getBlogEnableComment() {
        return blogEnableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_enable_comment
     *
     * @param blogEnableComment the value for tb_blog.blog_enable_comment
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogEnableComment(Byte blogEnableComment) {
        this.blogEnableComment = blogEnableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_is_deleted
     *
     * @return the value of tb_blog.blog_is_deleted
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Byte getBlogIsDeleted() {
        return blogIsDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_is_deleted
     *
     * @param blogIsDeleted the value for tb_blog.blog_is_deleted
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogIsDeleted(Byte blogIsDeleted) {
        this.blogIsDeleted = blogIsDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_create_time
     *
     * @return the value of tb_blog.blog_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getBlogCreateTime() {
        return blogCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_create_time
     *
     * @param blogCreateTime the value for tb_blog.blog_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogCreateTime(Date blogCreateTime) {
        this.blogCreateTime = blogCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_update_time
     *
     * @return the value of tb_blog.blog_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getBlogUpdateTime() {
        return blogUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_update_time
     *
     * @param blogUpdateTime the value for tb_blog.blog_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogUpdateTime(Date blogUpdateTime) {
        this.blogUpdateTime = blogUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_blog.blog_content
     *
     * @return the value of tb_blog.blog_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_blog.blog_content
     *
     * @param blogContent the value for tb_blog.blog_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}