package com.cyong.model;

import java.util.Date;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_name
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_value
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date configCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date configUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_id
     *
     * @return the value of tb_config.config_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_id
     *
     * @param configId the value for tb_config.config_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_name
     *
     * @return the value of tb_config.config_name
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_name
     *
     * @param configName the value for tb_config.config_name
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_value
     *
     * @return the value of tb_config.config_value
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_value
     *
     * @param configValue the value for tb_config.config_value
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_create_time
     *
     * @return the value of tb_config.config_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getConfigCreateTime() {
        return configCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_create_time
     *
     * @param configCreateTime the value for tb_config.config_create_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setConfigCreateTime(Date configCreateTime) {
        this.configCreateTime = configCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_update_time
     *
     * @return the value of tb_config.config_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getConfigUpdateTime() {
        return configUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_update_time
     *
     * @param configUpdateTime the value for tb_config.config_update_time
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setConfigUpdateTime(Date configUpdateTime) {
        this.configUpdateTime = configUpdateTime;
    }
}