package com.cyong.model;

import java.util.Date;

public class LeaveMessageRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer lmrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_answererId
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer lmrAnswererid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_fatherid
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Integer lmrFatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_date
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Date lmrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_is_read
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private Byte lmrIsRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leave_message_record.lmr_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    private String lmrContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_id
     *
     * @return the value of tb_leave_message_record.lmr_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getLmrId() {
        return lmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_id
     *
     * @param lmrId the value for tb_leave_message_record.lmr_id
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrId(Integer lmrId) {
        this.lmrId = lmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_answererId
     *
     * @return the value of tb_leave_message_record.lmr_answererId
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getLmrAnswererid() {
        return lmrAnswererid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_answererId
     *
     * @param lmrAnswererid the value for tb_leave_message_record.lmr_answererId
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrAnswererid(Integer lmrAnswererid) {
        this.lmrAnswererid = lmrAnswererid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_fatherid
     *
     * @return the value of tb_leave_message_record.lmr_fatherid
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Integer getLmrFatherid() {
        return lmrFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_fatherid
     *
     * @param lmrFatherid the value for tb_leave_message_record.lmr_fatherid
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrFatherid(Integer lmrFatherid) {
        this.lmrFatherid = lmrFatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_date
     *
     * @return the value of tb_leave_message_record.lmr_date
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Date getLmrDate() {
        return lmrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_date
     *
     * @param lmrDate the value for tb_leave_message_record.lmr_date
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrDate(Date lmrDate) {
        this.lmrDate = lmrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_is_read
     *
     * @return the value of tb_leave_message_record.lmr_is_read
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public Byte getLmrIsRead() {
        return lmrIsRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_is_read
     *
     * @param lmrIsRead the value for tb_leave_message_record.lmr_is_read
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrIsRead(Byte lmrIsRead) {
        this.lmrIsRead = lmrIsRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leave_message_record.lmr_content
     *
     * @return the value of tb_leave_message_record.lmr_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public String getLmrContent() {
        return lmrContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leave_message_record.lmr_content
     *
     * @param lmrContent the value for tb_leave_message_record.lmr_content
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    public void setLmrContent(String lmrContent) {
        this.lmrContent = lmrContent == null ? null : lmrContent.trim();
    }
}