package com.cyong.dao;

import com.cyong.model.BlogTagRelation;

public interface BlogTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int deleteByPrimaryKey(Long btrelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insert(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insertSelective(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    BlogTagRelation selectByPrimaryKey(Long btrelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKeySelective(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKey(BlogTagRelation record);
}