package com.cyong.dao;

import com.cyong.model.DailySpeech;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface DailySpeechMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int deleteByPrimaryKey(Integer dspeechId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insert(DailySpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insertSelective(DailySpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    DailySpeech selectByPrimaryKey(Integer dspeechId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKeySelective(DailySpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(DailySpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_speech
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKey(DailySpeech record);

    int selectDailySpeechNum();


    List<DailySpeech> vagueSearchDS(String dsKey,String sortField,String sortOrder );

    List<DailySpeech> searchAllDS();


}