package com.cyong.dao;

import com.cyong.model.Link;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int deleteByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    Link selectByPrimaryKey(Integer linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_link
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKey(Link record);

    int selectLinkNum();

    List<Link> vagueSearchLink(String searchKey,String sortField,String sortOrder,List<String> linkKinds);


}