package com.cyong.dao;

import com.cyong.model.Tag;
import com.cyong.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    Tag selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbggenerated Mon Oct 25 11:12:50 CST 2021
     */
    int updateByPrimaryKey(Tag record);

    List<Tag> vagueSearchByTagName(String tagName);
}